#SFL YAML configuration
#default configuration
project:
  name: 'Example Solar Farm'


#Overall details for the solar farm site
site:
  azimuth: 0 #angle from true north for rows, set to 0 for no rotation
  setback: 10 #meters to set rows back from edge, set to 0 for no setback


#Configuration for roads within the solar farm
roads:
  perimeter:
    road-width: 5 #m, width of perimeter roadway, set to 0 if not required
    clear-width: 8 #m, width of clearway for road, must be >=road-width
    turn-radius: 0 #m, minimum turn radius of the roadway. 0=no smoothing


solar:
  module:
    dim-length: 2 #m, long side of module length
    dim-width: 1 #m, short side of module length
    power-stc: 500 #W, STC power of the pv module being used
  
  spacing:
    post-to-post: 6 #m, spacing between center of solar row and its neighbour
    edge-offset: 0 #m, one-off shift for all solar rows from edge
  
  strings:
    mods-per-string: 27

  rows:
    n-modules-updown: 1
    portrait-mount: true
    space-end-row-row: 2 #m, space between rows (not rows and roads)
    space-end-row-road: 4 #m, space between end of row and roadway
    align: 'bottom' #options 'top','middle','bottom', how align rows based on strip
    types:
      - id: '3'
        strings-on-row: 3 #number of strings on this row total
        space-between-modules: 0.03 #m, space between adjacent rows
        extra-space: 3.2 #m, one-off addition to row length (for slew motor etc)
      - id: '2'
        strings-on-row: 2 #number of strings on this row total
        space-between-modules: 0.03 #m, space between adjacent rows
        extra-space: 3.2 #m, one-off addition to row length (for slew motor etc)
      - id: '1'
        strings-on-row: 1 #number of strings on this row total
        space-between-modules: 0.03 #m, space between adjacent rows
        extra-space: 3.2 #m, one-off addition to row length (for slew motor etc)
    layout-templates: 
    #Use the id from above, r for road. [] means repeat this if possible
    #This is in order of preference, with highest preference at top
      - '[33r]33' #Try 2x 3 string rows + road, ending with 2x 3 string rows
      - '[33r]3' #Try 2x 3 string rows + road, ending with 1x 3 string row
      - '[33r]2' #Try 2x 3 string rows + road, ending with 1x 2 string row
      - '[33r]2' #Try 2x 3 string rows + road, ending with 1x 2 string row
      # - '[3r]3' #Try 2x 3 string rows + road, ending with 1x 2 string row
      # - '[3r]2' #Try 2x 3 string rows + road, ending with 1x 2 string row
      # - '[3r]1' #Try 2x 3 string rows + road, ending with 1x 2 string row
      - '3' #Try 1x 3 string row
      - '2' #Try 1x 2 string row
      - '1' #Try 1x 2 string row


   
